### ISSUE TITLE
[Evento] - Hacktoberfest 2020

### ISSUE THREAD

**Issue by Perkles** [codered-co/codered-co#55]
![001](https://user-images.githubusercontent.com/18516908/91886051-1ebd6b80-ec5f-11ea-9366-d5d4f573fa06.png)

## O evento 🏛️ 

Durante o mês de outubro ocorre o [Hacktoberfest](https://hacktoberfest.digitalocean.com/) e esse ano a Codered irá participar 🎉. Durante todas as sextas feiras de outubro irá ocorrer uma live na [Twitch](https://www.twitch.tv/otavioperkles) as 20h falando sobre o que é o Hacktoberfest, como participar, dar dicas de repositórios para colaborar e compartilhar experiências. 

Para isso foi aberto um pedido de patrocínio no GitHub de 100 US$, 1 Mochila e 4 cupons de camisas.

## Distribuição dos prêmios 👕 

Abro aqui a discussão de como será feita a distribuição dos prêmios. Minha sugestão é a seguinte:
 - Ganha um cupom de camisa o participante que mostrar que fez uma contribuição em um projeto open source durante o evento 
 - No primeiro ou ultimo dia faremos um Kahoot, quem ganhar leva a mochila
 - Ganha uma pizza e um refri quem mostrar que fez uma contribuição em um projeto open source durante o evento (Itaperuna)

## Participantes 👩‍💻 

Estou abrindo aqui para quem quiser participar das lives, fazendo arte, ou ate mesmo divulgando o evento em seus perfis pessoais. 

Para participar da Live verifique se atende os requisitos:
 - Saber do que se trata o evento ou ter vontade de aprender sobre
 - Microfone de qualidade aceitável
 - Dispor de silencio na hora do evento
 - Uma webcam
 - Uma conta no discord

Caso queira ajudar -assign yourself- nessa Issue.

## TODO

- [x] Criar post sobre o evento com informações detalhadas no site #56 
- [x] Criar arte da stream #57 
- [x] Criar arte das redes sociais #58 

## Apoio 🤝 

[Noroeste Valley](https://noroestevalley.com.br/) 
GitHub

**Comment by gussouzauni** [comment]
Evento muito bacana, ansioso pela data!
